// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241108171131_AddDayModel")]
    partial class AddDayModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("backend.Models.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("TradingSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TradingSessionId");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("backend.Models.FiveMinuteBar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DayId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.ToTable("FiveMinuteBars");
                });

            modelBuilder.Entity("backend.Models.TradingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentBarIndex")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CurrentProfitLoss")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasOpenOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalProfitLoss")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingDay")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TradingSessions");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalProfit")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTradingDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.Day", b =>
                {
                    b.HasOne("backend.Models.TradingSession", "TradingSession")
                        .WithMany("Days")
                        .HasForeignKey("TradingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradingSession");
                });

            modelBuilder.Entity("backend.Models.FiveMinuteBar", b =>
                {
                    b.HasOne("backend.Models.Day", null)
                        .WithMany("FiveMinuteBars")
                        .HasForeignKey("DayId");
                });

            modelBuilder.Entity("backend.Models.TradingSession", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithOne("CurrentTradingSession")
                        .HasForeignKey("backend.Models.TradingSession", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Day", b =>
                {
                    b.Navigation("FiveMinuteBars");
                });

            modelBuilder.Entity("backend.Models.TradingSession", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("CurrentTradingSession");
                });
#pragma warning restore 612, 618
        }
    }
}
